apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world-python
spec:
  replicas: 7
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - name: hello-world-python
        image: nithishkumarrn/helloworld-demo-python:v1
        ports:
        - containerPort: 8080
